// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTaxonomies(t *testing.T) {
	t.Parallel()

	query := Taxonomies()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTaxonomiesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTaxonomiesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Taxonomies().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTaxonomiesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TaxonomySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTaxonomiesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TaxonomyExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Taxonomy exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TaxonomyExists to return true, but got false.")
	}
}

func testTaxonomiesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	taxonomyFound, err := FindTaxonomy(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if taxonomyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTaxonomiesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Taxonomies().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTaxonomiesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Taxonomies().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTaxonomiesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	taxonomyOne := &Taxonomy{}
	taxonomyTwo := &Taxonomy{}
	if err = randomize.Struct(seed, taxonomyOne, taxonomyDBTypes, false, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}
	if err = randomize.Struct(seed, taxonomyTwo, taxonomyDBTypes, false, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = taxonomyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = taxonomyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Taxonomies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTaxonomiesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	taxonomyOne := &Taxonomy{}
	taxonomyTwo := &Taxonomy{}
	if err = randomize.Struct(seed, taxonomyOne, taxonomyDBTypes, false, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}
	if err = randomize.Struct(seed, taxonomyTwo, taxonomyDBTypes, false, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = taxonomyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = taxonomyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func taxonomyBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func taxonomyAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Taxonomy) error {
	*o = Taxonomy{}
	return nil
}

func testTaxonomiesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Taxonomy{}
	o := &Taxonomy{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, taxonomyDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Taxonomy object: %s", err)
	}

	AddTaxonomyHook(boil.BeforeInsertHook, taxonomyBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	taxonomyBeforeInsertHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.AfterInsertHook, taxonomyAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	taxonomyAfterInsertHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.AfterSelectHook, taxonomyAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	taxonomyAfterSelectHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.BeforeUpdateHook, taxonomyBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	taxonomyBeforeUpdateHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.AfterUpdateHook, taxonomyAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	taxonomyAfterUpdateHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.BeforeDeleteHook, taxonomyBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	taxonomyBeforeDeleteHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.AfterDeleteHook, taxonomyAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	taxonomyAfterDeleteHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.BeforeUpsertHook, taxonomyBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	taxonomyBeforeUpsertHooks = []TaxonomyHook{}

	AddTaxonomyHook(boil.AfterUpsertHook, taxonomyAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	taxonomyAfterUpsertHooks = []TaxonomyHook{}
}

func testTaxonomiesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTaxonomiesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(taxonomyColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTaxonomiesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTaxonomiesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TaxonomySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTaxonomiesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Taxonomies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	taxonomyDBTypes = map[string]string{`ID`: `integer`, `LanguageKey`: `character varying`, `Key`: `character varying`, `Value`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_               = bytes.MinRead
)

func testTaxonomiesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(taxonomyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(taxonomyAllColumns) == len(taxonomyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTaxonomiesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(taxonomyAllColumns) == len(taxonomyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Taxonomy{}
	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, taxonomyDBTypes, true, taxonomyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(taxonomyAllColumns, taxonomyPrimaryKeyColumns) {
		fields = taxonomyAllColumns
	} else {
		fields = strmangle.SetComplement(
			taxonomyAllColumns,
			taxonomyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TaxonomySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTaxonomiesUpsert(t *testing.T) {
	t.Parallel()

	if len(taxonomyAllColumns) == len(taxonomyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Taxonomy{}
	if err = randomize.Struct(seed, &o, taxonomyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Taxonomy: %s", err)
	}

	count, err := Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, taxonomyDBTypes, false, taxonomyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Taxonomy struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Taxonomy: %s", err)
	}

	count, err = Taxonomies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
